apiVersion: v1
kind: Service
metadata:
  name: my-spring-app
spec:
  selector:
    app: my-spring-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
      - name: my-spring-appget
        image: israelglez1992/my-spring-app:latest
        ports:
        - containerPort: 8080

