apiVersion: batch/v1
kind: Job
metadata:
  name: micro-job-edgar
spec:
  template:
    metadata:
      name: micro-job-edgar
      labels:  
        app: micro-job-edgar
    spec:
      containers: 
      - name: micro-container
        image: israelglez1992/my-spring-app
        ports:
        - containerPort: 8080
        env:
          - name: USERNAME_SMTP
            value: A
          - name: PASSWORD_SMTP
            value: B
      restartPolicy: Never
  backoffLimit: 2

---
apiVersion: v1
kind: Service
metadata:
  name: micro-srv-edgar
spec:
  selector:
    app: micro-job-edgar
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
